from sage.all import *

#Question 5

S3 = SymmetricGroup(3)

gen_1 = S3((1, 2))  
gen_2 = S3((1, 2, 3))


G = S3.subgroup([gen_1, gen_2])

# Check if the subgroup is equal to S3
print(f"Is the subgroup generated by {(gen_1, gen_2)} equal to S3? {G == S3}")

#Question 6

D16 = DihedralGroup(8)
D16.normal_subgroups()

D14 = DihedralGroup(7)
D14.normal_subgroups()

D12 = DihedralGroup(6)
D12.normal_subgroups()

D10 = DihedralGroup(5)
D10.normal_subgroups()

D8 = DihedralGroup(4)
D8.normal_subgroups()

D6 = DihedralGroup(3)
D6.normal_subgroups()